/* Shared catalog data for workshop-planner.html and shop-3d-viewer.html.
   Plain (non-module) script — both a classic <script> page (workshop-planner.html) and an
   ES-module page (shop-3d-viewer.html) can read window.TOOL_SPECS / window.CATALOG_ITEMS.
   This is the single source of truth for tool specs and catalog dimensions; previously
   TOOL_SPECS was duplicated inline in both files and could drift out of sync. */
(function () {
    window.TOOL_SPECS = {
        'SawStop PCS175': { power: '1.75 HP', voltage: '110V / 220V', weight: '~440 lbs' },
        'SawStop ICS': { power: '3-5 HP', voltage: '220V (1 or 3-phase)', weight: '~600 lbs' },
        'Delta 36-L352': { power: '3 HP', voltage: '220V', weight: '~480 lbs' },
        'Laguna 14BX': { power: '1.75 HP', voltage: '110V / 220V', weight: '~275 lbs' },
        'Rikon 10-326': { power: '2 HP', voltage: '220V', weight: '~300 lbs' },
        'Grizzly G0513X2': { power: '3 HP', voltage: '220V', weight: '~455 lbs' },
        // Bandsaws -- Shop Fox, Harvey, Minimax (2026-08-09), real current models verified
        // against manufacturer/retailer pages.
        'Shop Fox W1706': { power: '1 HP', voltage: '115V / 230V', weight: '~305 lbs', buyUrl: 'https://www.maxtool.com/products/shop-fox-w1706-1-hp-14-bandsaw-w-extruded-aluminum-fence-rails-cabinet-stand' },
        'Shop Fox W1729': { power: '2 HP', voltage: '115V / 230V', weight: '~435 lbs', buyUrl: 'https://www.jbtools.com/woodstock-international-w1729-2-hp-19-bandsaw/' },
        'Shop Fox W1825': { power: '3 HP', voltage: '230V', weight: '~500 lbs', buyUrl: 'https://www.maxtool.com/products/shop-fox-w1825-19-3-hp-heavy-duty-band-saw' },
        'Shop Fox W1849': { power: '2 HP', voltage: '115V / 230V', weight: '~376 lbs', buyUrl: 'https://www.toolnut.com/shop-fox-w1849-14-inch-resaw-bandsaw.html' },
        'Shop Fox W1878': { power: '1/3 HP', voltage: '115V', weight: '~49 lbs', buyUrl: 'https://www.jbtools.com/woodstock-international-w1878-9-benchtop-bandsaw/' },
        'Harvey Ambassador C14Pro': { power: '3 HP', voltage: '230V', weight: '~350 lbs', buyUrl: 'https://www.harveywoodworking.com/products/ambassador-c14pro-3hp-14-stain-less-bandsaw' },
        'Harvey Alpha HW615Pro': { power: '3 HP', voltage: '230V', weight: '~441 lbs', buyUrl: 'https://www.harveywoodworking.com/products/alpha-hw615pro-3hp-15-stain-less-bandsaw' },
        'Harvey Alpha A-15': { power: '3 HP', voltage: '230V', weight: '~694 lbs', buyUrl: 'https://www.harveywoodworking.com/products/alpha-a-15-3hp-15-intelligent-bandsaw' },
        'Minimax S 45N': { power: '2.5 HP', voltage: '230V', weight: '~444 lbs', buyUrl: 'https://www.scmgroup.com/en_US/scmwood/products/joinery-machines.c884/band-saws.895/minimax-s-45n.130085' },
        'Minimax S 440P': { power: '4.8 HP', voltage: '230V', weight: '~440 lbs', buyUrl: 'https://shop.scmgroup.com/scmwood-na/us/en/Catalogs/Catalog/SIZING/Bandsaws/formula-s-440p/p/S440P_COMP1' },
        'Minimax S 540P': { power: '4.8 HP', voltage: '230V', weight: '~550 lbs', buyUrl: 'https://shop.scmgroup.com/scmwood-na/us/en/Machines-catalog/Catalog/SIZING/Bandsaws/formula-s-540p/p/S540P_COMP1' },
        'Minimax S 640P': { power: '4.8 HP', voltage: '230V', weight: '~750 lbs', buyUrl: 'https://shop.scmgroup.com/scmwood-na/us/en/Catalogs/Catalog/SIZING/Bandsaws/formula-s-640p/p/S640P_COMP3' },
        // Bandsaws -- Powermatic, JET, Delta (2026-08-09). Delta's current stationary bandsaw
        // lineup is genuinely down to one model (28-400) -- checked deltamachinery.com's
        // category page, site search, and retailer listings; a Lowe's-only "13.75-in 8-Amp"
        // SKU turned up with no confirmable model number against any manufacturer source, so
        // it was left out rather than guessed at.
        'Powermatic PWBS-14CS': { power: '1.5 HP', voltage: '115V / 230V', weight: '~250 lbs', buyUrl: 'https://www.powermatic.com/14-bandsaw-with-stand-and-riser-block-pwbs-14cs' },
        'Powermatic PM1500': { power: '3 HP', voltage: '230V', weight: '~394 lbs', buyUrl: 'https://www.powermatic.com/pm1500-bandsaw-3hp-1ph-230v' },
        'Powermatic PM1800BT': { power: '5 HP', voltage: '230V', weight: '~840 lbs', buyUrl: 'https://www.powermatic.com/pm1800bt-18-inch-woodworking-bandsaw-with-armorglide-5-hp-1ph-230v' },
        'Powermatic PM2013B': { power: '5 HP', voltage: '230V', weight: '~860 lbs', buyUrl: 'https://www.powermatic.com/pm2013b-3-20-bandsaw-5hp-3ph-230' },
        'Powermatic PM2415B': { power: '5 HP', voltage: '230V', weight: '~974 lbs', buyUrl: 'https://www.powermatic.com/pm2415b-24-bandsaw-5hp-1ph-230v' },
        'JET JWB-10': { power: '0.5 HP', voltage: '115V', weight: '~83 lbs', buyUrl: 'https://jettools.com/jwb-10-10-open-stand-bandsaw' },
        'JET JWBS-14CS': { power: '1 HP', voltage: '115V / 230V', weight: '~185 lbs', buyUrl: 'https://jettools.com/14-closed-stand-bandsaw-1hp-1ph-115-230v' },
        'JET JWBS-14SFX': { power: '1.75 HP', voltage: '115V / 230V', weight: '~272 lbs', buyUrl: 'https://jettools.com/jwbs-14sfx-14-bandsaw-1-3-4hp-115-230v' },
        'JET JWBS-15': { power: '1.75 HP', voltage: '115V / 230V', weight: '~382 lbs', buyUrl: 'https://jettools.com/jet-15in-1-75hp-bandsaw-w-cast-iron-fence-system' },
        'JET JWBS-18SFX': { power: '1.75 HP', voltage: '115V', weight: '~383 lbs', buyUrl: 'https://jettools.com/jwbs-18sfx-18-bandsaw-1-3-4-hp-1ph-115v' },
        'JET JWBS-20-5': { power: '5 HP', voltage: '230V', weight: '~616 lbs', buyUrl: 'https://jettools.com/jwbs-20-5-20-bandsaw-5hp-230v' },
        'Delta 28-400': { power: '1 HP', voltage: '115V / 230V', weight: '~165 lbs', buyUrl: 'https://deltamachinery.com/product/28-400-14-in-1-hp-steel-frame-bandsaw/' },
        'Powermatic PJ882': { power: '2 HP', voltage: '220V', weight: '~475 lbs' },
        'Powermatic 201HH': { power: '3 HP', voltage: '220V', weight: '~450 lbs' },
        'Hammer A3-31': { power: '4 HP', voltage: '220V / 3-phase', weight: '~750 lbs' },
        'Grizzly G0771Z': { power: '1.5 HP', voltage: '110V / 220V', weight: '~200 lbs' },
        'JET 22-44 Sander': { power: '3/4 HP', voltage: '110V', weight: '~250 lbs' },
        'SuperMax 19-38': { power: '5 HP', voltage: '220V', weight: '~600 lbs' },
        'Powermatic PM2800B': { power: '1 HP', voltage: '110V / 220V', weight: '~400 lbs' },
        'General 75-510 M1': { power: '3/4 HP', voltage: '110V', weight: '~200 lbs' },
        'Powermatic 3520C': { power: '2 HP', voltage: '220V', weight: '~600 lbs' },
        'JET JWL-1640EVS': { power: '1.5 HP', voltage: '110V / 220V', weight: '~350 lbs' },
        'SawStop RT': { power: 'N/A (table)', voltage: 'N/A', weight: '~120 lbs' },
        'Kreg PRS2100': { power: 'N/A (table)', voltage: 'N/A', weight: '~85 lbs' },
        'Festool Kapex KS 120': { power: '15A', voltage: '120V', weight: '~62 lbs + stand' },
        'Bosch GTS1041A': { power: '15A', voltage: '120V', weight: '~13 lbs + stand' },
        'JET DC-1100VX': { power: '1.5 HP', voltage: '110V / 220V', weight: '~230 lbs' },
        'Oneida Super Dust Deputy XL': { power: 'Passive cyclone', voltage: 'N/A', weight: '~25 lbs' },
        '4in Dust Duct 2ft': { power: 'N/A', voltage: 'N/A', weight: '~1 lb' },
        '4in Dust Duct 4ft': { power: 'N/A', voltage: 'N/A', weight: '~2 lbs' },
        '4in Dust Duct 6ft': { power: 'N/A', voltage: 'N/A', weight: '~3 lbs' },
        '4in Dust Duct 8ft': { power: 'N/A', voltage: 'N/A', weight: '~4 lbs' },
        '4in Dust Duct 10ft': { power: 'N/A', voltage: 'N/A', weight: '~5 lbs' },
        '6in Dust Duct 2ft': { power: 'N/A', voltage: 'N/A', weight: '~1.5 lbs' },
        '6in Dust Duct 4ft': { power: 'N/A', voltage: 'N/A', weight: '~3 lbs' },
        '6in Dust Duct 6ft': { power: 'N/A', voltage: 'N/A', weight: '~4.5 lbs' },
        '6in Dust Duct 8ft': { power: 'N/A', voltage: 'N/A', weight: '~6 lbs' },
        '6in Dust Duct 10ft': { power: 'N/A', voltage: 'N/A', weight: '~7.5 lbs' },
        'Blast Gate': { power: 'N/A', voltage: 'N/A', weight: '~1 lb' },
        '6in Blast Gate': { power: 'N/A', voltage: 'N/A', weight: '~1.5 lbs' },
        '4in Duct Drop': { power: 'N/A', voltage: 'N/A', weight: '~1 lb' },
        '6in Duct Drop': { power: 'N/A', voltage: 'N/A', weight: '~1.5 lbs' },
        '4in Duct Elbow': { power: 'N/A', voltage: 'N/A', weight: '~1 lb' },
        '6in Duct Elbow': { power: 'N/A', voltage: 'N/A', weight: '~1.5 lbs' },
        '4in Duct Y-Joint': { power: 'N/A', voltage: 'N/A', weight: '~1.2 lbs' },
        '6in Duct Y-Joint': { power: 'N/A', voltage: 'N/A', weight: '~1.8 lbs' },
        '4in Duct T-Joint': { power: 'N/A', voltage: 'N/A', weight: '~1.2 lbs' },
        '6in Duct T-Joint': { power: 'N/A', voltage: 'N/A', weight: '~1.8 lbs' },
        '4in Pipe Bracket': { power: 'N/A', voltage: 'N/A', weight: '~0.3 lbs' },
        '6in Pipe Bracket': { power: 'N/A', voltage: 'N/A', weight: '~0.4 lbs' },
        'LED Shop Light 4ft': { power: '40W', voltage: '110V', weight: '~6 lbs' },
        'High Bay LED Fixture': { power: '150W', voltage: '110V / 220V', weight: '~12 lbs' },
        'Adjustable Task Light': { power: '10W', voltage: '110V', weight: '~3 lbs' },
        'Shapeoko Pro XXL': { power: 'NEMA 23 steppers', voltage: '110V', weight: '~110 lbs' },
        'Glowforge Pro': { power: '45W laser', voltage: '120V', weight: '~80 lbs' },
        'Bambu Lab X1 Carbon': { power: '350W', voltage: '120V', weight: '~24 lbs' },
        'Prusa MK4': { power: '240W', voltage: '110V / 220V', weight: '~18 lbs' },
        'Creality K1 Max': { power: '1000W', voltage: '110V / 220V', weight: '~26 lbs' },
        'Elegoo Saturn 4 Ultra': { power: '200W', voltage: '110V', weight: '~15 lbs' },
        'Assembly Table': { power: 'N/A', voltage: 'N/A', weight: '~150 lbs' },
        'Kreg Mobile Project Center': { power: 'N/A', voltage: 'N/A', weight: '~90 lbs' },
        'Milwaukee PACKOUT Rolling Box': { power: 'N/A', voltage: 'N/A', weight: '~20 lbs empty' },
        'DEWALT TOUGHSYSTEM 2.0': { power: 'N/A', voltage: 'N/A', weight: '~29 lbs empty' },
        'Craftsman 26in Rolling Cabinet': { power: 'N/A', voltage: 'N/A', weight: '~150 lbs empty' },
        'Kobalt 41in Rolling Chest': { power: 'N/A', voltage: 'N/A', weight: '~230 lbs empty' },
        'US General 56in Roller Cabinet': { power: 'N/A', voltage: 'N/A', weight: '~340 lbs empty' },
        'Husky 52in Mobile Workbench': { power: 'N/A', voltage: 'N/A', weight: '~300 lbs empty' },
        'Snap-on KRL1023 Classic 78': { power: 'N/A', voltage: 'N/A', weight: '~700 lbs empty' },
        'Husky 72in Tool Chest Combo': { power: 'N/A', voltage: 'N/A', weight: '~650 lbs empty' },

        // Researched 2026-07-18 for the catalog expansion — real current models with verified
        // specs from manufacturer/retailer pages, spanning budget/mid/premium tiers per
        // category. buyUrl links out to a real product page (no pricing shown per product
        // decision — prices go stale fast and a wrong number is worse than none).
        'DeWalt DWE7491RS': { power: '15A', voltage: '120V', weight: '~90 lbs (w/ stand)', buyUrl: 'https://www.dewalt.com/en-us/product/dwe7491rs/10-jobsite-table-saw-and-rolling-stand' },
        'SKIL TS6307-00': { power: '15A', voltage: '120V', weight: '~65 lbs', buyUrl: 'https://www.skil.com/products/15-amp-10inch-table-saw-ts6307-00' },
        'RIDGID R4518': { power: '15A', voltage: '120V', weight: '~75 lbs', buyUrl: 'https://www.homedepot.com/p/RIDGID-15-Amp-10-in-Portable-Corded-Jobsite-Table-Saw-with-Folding-Stand-R4518/309413142' },
        'Grizzly G0715P': { power: '2 HP', voltage: '110V / 220V', weight: '~393 lbs', buyUrl: 'https://cdn0.grizzly.com/specsheets/g0715p_ds.pdf' },
        'Powermatic PM1000': { power: '1.75 HP', voltage: '115V / 230V', weight: '~289 lbs', buyUrl: 'https://www.rockler.com/powermatic-pm1000-1-3-4-hp-table-saw-1-phase-with-30-accu-fence-system' },
        'Grizzly G0690': { power: '3 HP', voltage: '220V', weight: '~507 lbs', buyUrl: 'https://cdn0.grizzly.com/specsheets/g0690_ds.pdf' },
        'DeWalt DWS779': { power: '15A', voltage: '120V', weight: '~56 lbs', buyUrl: 'https://www.dewalt.com/en-us/product/dws779/12-double-bevel-sliding-compound-miter-saw' },
        'Bosch GCM12SD': { power: '15A', voltage: '120V', weight: '~65 lbs', buyUrl: 'https://www.boschtools.com/us/en/products/gcm12sd-060166501C' },
        'Makita LS1019L': { power: '15A', voltage: '120V', weight: '~58 lbs', buyUrl: 'https://makitatools.com/products/details/LS1019L' },
        'Metabo HPT C10FCGS': { power: '15A', voltage: '120V', weight: '~24 lbs', buyUrl: 'https://www.metabo-hpt.com/products/product/10-compound-miter-saw-c10fcgs-metabo-hpt' },
        // Crosscut & Miter -- deeper pass across Milwaukee, RIDGID, Craftsman, Metabo HPT,
        // Makita, DeWalt, Bosch, Festool, SKILSAW (2026-08-09). Footprints are saw+stand
        // deployed dimensions; heights include an estimated blade-guard-up clearance allowance
        // on top of each stand's structural height since no manufacturer publishes a combined
        // figure. Hitachi confirmed fully rebranded to Metabo HPT in the US -- no separate
        // Hitachi-branded saw exists to add.
        'Milwaukee 2734-20': { power: '18V (cordless, ~15A equiv.)', voltage: '18V', weight: '~76 lbs (saw + stand)', buyUrl: 'https://www.milwaukeetool.com/products/details/m18-fuel-dual-bevel-sliding-compound-miter-saw/2734-20' },
        'Milwaukee 2739-21HD': { power: '18V (cordless, ~15A equiv.)', voltage: '18V', weight: '~83 lbs (saw + stand)', buyUrl: 'https://www.milwaukeetool.com/products/details/m18-fuel-12-dual-bevel-sliding-compound-miter-saw/2739-21hd' },
        'RIDGID R4222': { power: '15A', voltage: '120V', weight: '~131 lbs (saw + stand)', buyUrl: 'https://powertools.ridgid.com/products/648846071787' },
        'Craftsman CMXEMAX69434501': { power: '15A', voltage: '120V', weight: '~120 lbs (saw + stand)', buyUrl: 'https://www.craftsman.com/en-us/product/cmxemax69434501/craftsman-10-inch-corded-electric-single-bevel-sliding-miter-saw-15-amp' },
        'Metabo HPT C12RSH2S': { power: '15A', voltage: '120V', weight: '~109 lbs (saw + stand)', buyUrl: 'https://www.metabo-hpt.com/products/product/12-sliding-dual-compound-miter-saw-with-laser-marker-c12rsh2s-metabo-hpt' },
        'Metabo HPT C3612DRAQ4': { power: '36V MultiVolt (cordless)', voltage: '36V', weight: '~104 lbs (saw + stand)', buyUrl: 'https://www.metabo-hpt.com/products/product/36v-multivolt--12--dual-bevel-sliding-miter-saw-w--torque-boost-technology-(tool-body-only)---metabo-hpt-c3612draq4' },
        'Makita LS1219L': { power: '15A', voltage: '120V', weight: '~100 lbs (saw + stand)', buyUrl: 'https://www.coastaltool.com/products/makita-ls1219l-12-miter-saw' },
        'Makita XSL08PT': { power: '36V (18Vx2, cordless)', voltage: '36V', weight: '~104 lbs (saw + stand)', buyUrl: 'https://www.amazon.com/Makita-XSL08PT-Lithium-Ion-Brushless-Dual-Bevel/dp/B07RJGM39V' },
        'DeWalt DHS790AT2': { power: '60V Max FlexVolt (cordless)', voltage: '60V', weight: '~123 lbs (saw + stand)', buyUrl: 'https://www.coastaltool.com/products/dewalt-dhs790at2-12-double-bevel-sliding-compound-flexvolt-miter-saw-kit' },
        'DeWalt DCS781X1': { power: '60V Max (cordless)', voltage: '60V', weight: '~118 lbs (saw + stand)', buyUrl: 'https://www.dewalt.com/en-us/product/dcs781x1/dewalt-60v-max-brushless-cordless-12-double-bevel-sliding-miter-saw-kit' },
        'Bosch GCM18V-12GDCN': { power: '18V (cordless)', voltage: '18V', weight: '~136 lbs (saw + stand)', buyUrl: 'https://www.boschtools.com/us/en/products/gcm18v-12gdcn-0601B43014' },
        'Festool KSC 60 EB-Basic': { power: '18V x2 (cordless)', voltage: '18V x2', weight: '~38 lbs (saw only)', buyUrl: 'https://www.woodcraft.com/products/festool-cordless-kapex-sliding-compound-miter-saw-ksc-60-eb-basic' },
        'Skilsaw SPT88-01': { power: '15A', voltage: '120V', weight: '~51 lbs (saw only)', buyUrl: 'https://www.skil.com/products/wormdrive-dual-bevel-miter-saw-spt88-01' },
        'Rikon 10-305': { power: '1/3 HP', voltage: '120V', weight: '~76 lbs', buyUrl: 'https://rikontools.com/product/model-10-305-10%E2%80%B3-bandsaw/' },
        'Grizzly G0555LX': { power: '1 HP', voltage: '110V', weight: '~218 lbs', buyUrl: 'https://cdn0.grizzly.com/specsheets/g0555lx_ds.pdf' },
        'DeWalt DW735X': { power: '15A', voltage: '120V', weight: '~102 lbs', buyUrl: 'https://www.dewalt.com/en-us/product/dw735x/13-3-knife-two-speed-thickness-planer' },
        'JET JWJ-8CS': { power: '2 HP', voltage: '230V', weight: '~398 lbs', buyUrl: 'https://www.homedepot.com/p/Jet-JWJ-8CS-8-in-Closed-Stand-Jointer-Kit-718200K/306002034' },
        'Cutech 40160HB': { power: 'N/A (manual feed)', voltage: 'N/A', weight: '~65 lbs', buyUrl: 'https://cutechtools.us/products/6-spiral-cutterhead-benchtop-jointer-black-table-cutech-40160hb' },
        'WEN 6502T': { power: '4.3A', voltage: '120V', weight: '~41 lbs', buyUrl: 'https://www.homedepot.com/p/WEN-4-3-Amp-Corded-4-in-x-36-in-Belt-and-6-in-Disc-Sander-with-Cast-Iron-Base-6502T/307346676' },
        'RIDGID EB4424': { power: '5A', voltage: '120V', weight: '~40 lbs', buyUrl: 'https://powertools.ridgid.com/products/648846050546' },
        'WEN 4210': { power: '3.2A', voltage: '120V', weight: '~45 lbs', buyUrl: 'https://www.amazon.com/WEN-4210-Drill-Press-10-Inch/dp/B005UKGLAS' },
        'Powermatic PM701': { power: '3/4 HP', voltage: '115V / 230V', weight: '~93 lbs', buyUrl: 'https://www.powermatic.com/pm701-mortiser-3-4hp-1ph-115-230v' },
        // Drilling & Boring -- deeper pass across JET, Grizzly, Shop Fox, Rikon, Delta, NOVA,
        // WEN, General Intl, Craftsman, Baileigh (2026-08-09). Wilton confirmed to sell zero
        // drill presses (current lineup is vises/clamps/striking tools only) -- excluded.
        'JET JDP-20S': { power: '1.5 HP', voltage: '115V', weight: '~220 lbs', buyUrl: 'https://jettools.com/20-in-smart-drill-press-jdp-20s' },
        'JET JDP-20MF': { power: '1.5 HP', voltage: '115V / 230V', weight: '~282 lbs', buyUrl: 'https://jettools.com/jdp-20mf-20-floor-drill-press-115-230v-1ph' },
        'JET JDP-17MF': { power: '3/4 HP', voltage: '115V', weight: '~187 lbs', buyUrl: 'https://jettools.com/17-drill-press' },
        'JET JDP-15B': { power: '3/4 HP', voltage: '115V', weight: '~154 lbs', buyUrl: 'https://jettools.com/15-benchtop-drill-press' },
        'JET JWDP-12': { power: '1/2 HP', voltage: '115V', weight: '~85 lbs', buyUrl: 'https://jettools.com/12-inch-benchtop-variable-speed-drill-press-jwdp-12' },
        'Grizzly G7948': { power: '1.5 HP', voltage: '120V', weight: '~303 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-20-floor-drill-press/g7948' },
        'Grizzly G0784': { power: '2 HP', voltage: '220V', weight: '~772 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-15-heavy-duty-floor-drill-press/g0784' },
        'Grizzly G0925': { power: '1/3 HP', voltage: '120V', weight: '~34 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-8-benchtop-drill-press/g0925' },
        'Grizzly T31739': { power: '1/3 HP', voltage: '120V', weight: '~88 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-12-variable-speed-benchtop-drill-press-with-laser/t31739' },
        'Grizzly G7945': { power: '1/2 HP', voltage: '120V', weight: '~97 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-34-benchtop-radial-drill-press/g7945' },
        'Shop Fox W1680': { power: '1 HP', voltage: '110V', weight: '~185 lbs', buyUrl: 'https://www.grizzly.com/products/shop-fox-17-floor-model-drill-press/w1680' },
        'Shop Fox M1039': { power: '1.5 HP', voltage: '110V', weight: '~317 lbs', buyUrl: 'https://www.grizzly.com/products/shop-fox-20-floor-drill-press/m1039' },
        'Shop Fox W1668': { power: '3/4 HP', voltage: '110V', weight: '~125 lbs', buyUrl: 'https://www.grizzly.com/products/shop-fox-13-1-4-benchtop-oscillating-drill-press/w1668' },
        'Rikon 30-230': { power: '1 HP', voltage: '120V', weight: '~188 lbs', buyUrl: 'https://rikontools.com/product/model-30-230-17-floor-drill-press/' },
        'Rikon 30-240': { power: '1 HP', voltage: '120V', weight: '~250 lbs', buyUrl: 'https://rikontools.com/product/model-30-240-20-floor-drill-press/' },
        'Rikon 30-120': { power: '1/2 HP', voltage: '120V', weight: '~102 lbs', buyUrl: 'https://rikontools.com/product/model-30-120-13-benchtop-drill-press/' },
        'Rikon 30-217': { power: '1.5 HP', voltage: '115V / 230V', weight: '~192 lbs', buyUrl: 'https://rikontools.com/product/model-30-217-17-vs-drill-press/' },
        'Delta 18-900L': { power: '3/4 HP', voltage: '120V', weight: '~240 lbs', buyUrl: 'https://deltamachinery.com/product/18-900l-18-in-laser-drill-press/' },
        'NOVA Voyager DVR': { power: '1.75-2 HP', voltage: '110V / 220V', weight: '~307 lbs', buyUrl: 'https://www.teknatool.com/products/drill-presses/nova-voyager-dvr-drill-press/' },
        'WEN 4208T': { power: '2.3A', voltage: '120V', buyUrl: 'https://wenproducts.com/products/wen-4208t-2-3-amp-8-inch-5-speed-benchtop-drill-press' },
        'WEN 4211': { power: '3.2A', voltage: '120V', buyUrl: 'https://wenproducts.com/products/wen-4211-3-2-amp-10-inch-5-speed-benchtop-drill-press-with-laser-and-keyless-chuck' },
        'WEN 4214T': { power: '5A', voltage: '120V', weight: '~85 lbs', buyUrl: 'https://wenproducts.com/products/wen-4214t-12-in-variable-speed-drill-press' },
        'WEN 4225T': { power: '8.6A', voltage: '120V', weight: '~154 lbs', buyUrl: 'https://wenproducts.com/products/wen-4225t-8-6-amp-15-inch-variable-speed-floor-standing-drill-press' },
        'WEN 4227T': { power: '13A', voltage: '120V', weight: '~214 lbs', buyUrl: 'https://wenproducts.com/products/wen-4227t-13-amp-17-inch-12-speed-floor-standing-drill-press' },
        'WEN 4233': { power: '6.2A', voltage: '120V', weight: '~105 lbs', buyUrl: 'https://wenproducts.com/products/wen-4233-6-2-amp-33-inch-radial-arm-drill-press-benchtop-design-with-5-speeds-and-cast-iron-construction' },
        'General Intl 75-155 M1': { power: '1/2 HP', voltage: '120V', weight: '~136 lbs', buyUrl: 'https://www.acmetools.com/general-international-15in-floor-commercial-mechanical-variable-speed-drill-press--3-4-hp-75-155-m1/626708751558.html' },
        'General Intl 75-260 M1': { power: '1 HP', voltage: '120V', weight: '~229 lbs', buyUrl: 'http://www.general.ca/products/1_general/75_drill/75-260.html' },
        'General Intl 75-500 M1': { power: '1 HP', voltage: '110V', weight: '~372 lbs', buyUrl: 'https://www.calfast.com/10426_0-GEN75-500-M1.html' },
        'General Intl 75-710 M1': { power: '1 HP', voltage: '220V', weight: '~161 lbs', buyUrl: 'https://www.acmetools.com/general-international-electronic-17in-variable-speed-drive-floor-drill-press-1-hp-75-710-m1/626708757109.html' },
        'Craftsman CMXEDAX69434601': { power: '4.1A', voltage: '120V', weight: '~53 lbs', buyUrl: 'https://www.craftsman.com/en-us/product/cmxedax69434601/10-benchtop-drill-press-41-amp' },
        'Baileigh DP-15VSF': { power: '1 HP', voltage: '115V', weight: '~450 lbs', buyUrl: 'https://www.baileigh.com/drill-press-dp-15vsf' },
        'Baileigh DP-1500G': { power: '3.5 HP', voltage: '220V (3-phase)', weight: '~963 lbs', buyUrl: 'https://www.baileigh.com/drill-press-dp-1500g' },
        'Baileigh DP-3814B': { power: '1/2 HP', voltage: '110V', weight: '~210 lbs', buyUrl: 'https://www.baileigh.com/dp-3814b-bench-top-drill-press' },
        'Baileigh DP-4016B': { power: '3/4 HP', voltage: '110V', weight: '~260 lbs', buyUrl: 'https://www.baileigh.com/dp-4016b-16-bench-top-drill-press' },
        'Baileigh DP-1375VS-110': { power: '2 HP', voltage: '110V', weight: '~706 lbs', buyUrl: 'https://www.baileigh.com/dp-1375vs-110-variable-speed-drill-press' },
        'JET JWL-1221VS': { power: '1 HP', voltage: '115V', weight: '~115 lbs', buyUrl: 'https://jettools.com/jwl-1221vs-12-x-21-variable-speed-wood-lathe' },
        'Grizzly G0733': { power: '2 HP', voltage: '240V', weight: '~547 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-18-x-47-heavy-duty-wood-lathe/g0733' },
        'Bosch RA1181': { power: 'N/A (table only)', voltage: 'N/A', weight: '~30 lbs', buyUrl: 'https://www.homedepot.com/p/Bosch-27-in-x-18-in-Aluminum-Top-Benchtop-Router-Table-with-2-1-2-in-Vacuum-Hose-Port-RA1181/100466926' },
        'Onefinity Journeyman': { power: 'NEMA23 steppers', voltage: '120V', weight: '~90 lbs', buyUrl: 'https://www.onefinitycnc.com/product-page/onefinity-journeyman' },
        'WEN DC3401': { power: '5.7A', voltage: '120V', weight: '~18.5 lbs', buyUrl: 'https://www.homedepot.com/p/WEN-5-7-Amp-660-CFM-Rolling-Dust-Collector-with-12-Gal-Bag-and-Optional-Wall-Mount-DC3401/320052090' },
        'Laguna C-Flux 2': { power: '2 HP', voltage: '220V', weight: '~301 lbs', buyUrl: 'https://lagunatools.com/classic/dust-collectors/c-flux-2/' },

        // Mechanical/automotive shop equipment — researched 2026-07-18 for the new Shop Type
        // (Woodworking/Mechanical/Both) feature. Some footprints are estimated where the
        // manufacturer doesn't publish one (flagged in tool-catalog-research.md); everything
        // else is verified against the manufacturer/retailer page linked in buyUrl.
        'BendPak XPR-10A': { power: 'N/A (electro-hydraulic)', voltage: '220V', weight: '~1,300 lbs', buyUrl: 'https://www.speedwaymotors.com/BendPak-XPR-10A-LP-2-Post-Lift-10-000-Pound-Lifting-Capacity,126981.html' },
        'BendPak HD-9': { power: 'N/A (electro-hydraulic)', voltage: '220V', weight: 'N/A', buyUrl: 'https://www.bendpak.com/car-lifts/four-post-lifts/hd-9/' },
        'BendPak MD-6XP': { power: 'N/A (air/hydraulic)', voltage: '110V power unit', weight: 'N/A', buyUrl: 'https://www.bendpak.com/car-lifts/mid-rise-scissor-lifts/md-6xp/' },
        'Ranger RML-1500XL': { power: 'N/A (air/hydraulic)', voltage: 'N/A', weight: '~808 lbs', buyUrl: 'https://www.bendpak.com/shop-equipment/motorcycle-lifts/rml-1500xl/' },
        'Hobart Handler 140': { power: '115V', voltage: '115V', weight: '~57 lbs', buyUrl: 'https://www.hobartwelders.com/equipment/welders/mig-gmaw/handler-140-mig-welder-m00169' },
        'Miller Multimatic 215': { power: '110/240V', voltage: '110/120/240V', weight: '~38 lbs', buyUrl: 'https://www.millerwelds.com/equipment/welders/multiprocess/multimatic-215-multiprocess-welder-m30090' },
        'California Air Tools 10020C': { power: '2 HP', voltage: '120V', weight: '~82.5 lbs', buyUrl: 'https://www.homedepot.com/p/California-Air-Tools-10-Gal-2-0-HP-Ultra-Quiet-and-Oil-Free-Electric-Air-Compressor-10020C/206644539' },
        'Ingersoll Rand 2475N7.5-V': { power: '7.5 HP', voltage: '230V', weight: '~611 lbs', buyUrl: 'https://www.homedepot.com/p/Ingersoll-Rand-Type-30-Reciprocating-80-Gal-7-5-HP-Electric-230-Volt-Single-Phase-Air-Compressor-2475N7-5-V/203751639' },
        'Torin T32002': { power: 'N/A (hydraulic)', voltage: 'N/A', weight: '~160 lbs', buyUrl: 'https://www.northerntool.com/products/torin-big-red-2-ton-folding-shop-crane-with-free-load-leveler-model-t32002-144847' },
        'Arcan XL20': { power: 'N/A (hydraulic)', voltage: 'N/A', weight: '~67 lbs', buyUrl: 'https://www.homedepot.com/p/Arcan-2-Ton-Floor-Jack-XL20/308313510' },
        'Torin TRA4055': { power: 'N/A (hydraulic)', voltage: 'N/A', weight: '~120 lbs', buyUrl: 'https://www.northerntool.com/products/torin-big-red-double-ram-transmission-jack-1-2-ton-35in-70-1-2in-lift-range-model-tra4055-104514' },
        'Coats 70X-AH': { power: '1.5 HP air motor', voltage: 'N/A', weight: '~700 lbs', buyUrl: 'https://www.myerstiresupply.com/coats-equipment/coats-tire-changers/coats-70x-tire-changer.html' },
        'Snap-on EPIQ 84in': { power: 'N/A', voltage: 'N/A', weight: 'N/A', buyUrl: 'https://shop.snapon.com/categories/84%22-Wide-EPIQ%E2%84%A2-Roll-Cabs/629487' },
        'Mac Tools Macsimizer': { power: 'N/A', voltage: 'N/A', weight: '~740 lbs shipping', buyUrl: 'https://www.mactools.com/collections/tool-storage' },

        // Plumbing layer — new 4th layer, works for every shop type (domain-agnostic)
        'Zurn Z415': { power: 'N/A', voltage: 'N/A', weight: 'N/A', buyUrl: 'https://www.zurn.com/products/drainage-interceptors/floor-drains/finish-floor-drains/z415b' },
        'Mustee 63M': { power: 'N/A', voltage: 'N/A', weight: 'N/A', buyUrl: 'https://www.homeperfect.com/mustee-63m-mop-sink-white-24-in-l.html' },
        'Rheem RTEX-13': { power: '13 kW', voltage: '240V', weight: '~8.5 lbs', buyUrl: 'https://www.homedepot.com/p/Rheem-Performance-13-kW-2-54-GPM-240-Volt-Self-Modulating-Electric-Tankless-Water-Heater-RETEX-13/300800566' },
        'NDS Dura Slope': { power: 'N/A', voltage: 'N/A', weight: 'N/A', buyUrl: 'https://www.ndspro.com/us/en/product/drainage/channel-and-trench-drains-and-grates/ds-097-dura-slope-channel-drain-60-in-to-64-in-invert-depth-6-in-wide-x-4-ft-long-x-78-in-deep' },
        'Woodford Model 65': { power: 'N/A', voltage: 'N/A', weight: 'N/A', buyUrl: 'https://www.supplyhouse.com/Woodford-65P-12-Model-65-12-3-4-FPT-Inlet-Freezeless-Automatic-Draining-Wall-Hydrant' },

        // Dust collection reducer — bridges a 4in run to a 6in run (see DUCT_PORTS/
        // getPortSizeClasses in workshop-planner.html for the port-matching logic)
        '4in-6in Duct Reducer': { power: 'N/A', voltage: 'N/A', weight: '~1 lb' },

        // Table Saws catalog expansion — researched 2026-08-09, real current models verified
        // against manufacturer/retailer pages. Manufacturers checked but excluded because they
        // no longer sell current table saws: Makita (discontinued entire US line), Steel City
        // Tool Works (original brand closed 2015), Baileigh Industrial (exited woodworking
        // equipment entirely in 2025). Footprint dims are estimated where not published.
        'Bosch 4100XC-10': { power: '15A', voltage: '120V', weight: '~94 lbs', buyUrl: 'https://www.boschtools.com/us/en/products/4100xc-10-0601B13016' },
        'Bosch GTS15-10': { power: '15A', voltage: '120V', weight: '~91 lbs', buyUrl: 'https://www.boschtools.com/us/en/products/gts15-10-0601B54013' },
        'Bosch GTS18V-08N': { power: '18V Brushless', voltage: '18V', weight: '~44 lbs', buyUrl: 'https://www.boschtools.com/us/en/products/gts18v-08n-0601B48014' },
        'Bosch GTS18V-08N14': { power: '18V Brushless', voltage: '18V', weight: '~44 lbs', buyUrl: 'https://www.boschtools.com/us/en/products/gts18v-08n14-0601B48015' },
        'Milwaukee 2736-20': { power: '18V Brushless', voltage: '18V', weight: '~42 lbs', buyUrl: 'https://www.milwaukeetool.com/products/details/m18-fuel-8-1-4-table-saw-w-one-key/2736-20' },
        'Milwaukee 2736-21HD': { power: '18V Brushless', voltage: '18V', weight: '~42 lbs', buyUrl: 'https://www.milwaukeetool.com/products/details/m18-fuel-8-1-4-table-saw-w-one-key-kit/2736-21hd' },
        'Ryobi RTS23': { power: '15A', voltage: '120V', weight: '~51 lbs', buyUrl: 'https://www.homedepot.com/p/RYOBI-15-Amp-10-in-Expanded-Capacity-Portable-Corded-Table-Saw-With-Rolling-Stand-RTS23/309412848' },
        'Ryobi RTS12': { power: '15A', voltage: '120V', weight: '~55 lbs', buyUrl: 'https://www.homedepot.com/p/RYOBI-15-Amp-10-in-Compact-Portable-Corded-Jobsite-Table-Saw-with-Folding-Stand-RTS12/309412842' },
        'Ryobi RTS08': { power: '13A', voltage: '120V', weight: '~50 lbs', buyUrl: 'https://www.homedepot.com/p/RYOBI-13-Amp-8-1-4-in-Compact-Portable-Corded-Jobsite-Table-Saw-No-Stand-RTS08/309412837' },
        'Ryobi PBLTS01K': { power: '18V Brushless', voltage: '18V', weight: '~33 lbs', buyUrl: 'https://www.homedepot.com/p/RYOBI-ONE-HP-18V-Brushless-Cordless-8-1-4-in-Compact-Portable-Jobsite-Table-Saw-Kit-with-2-4-0-Ah-Batteries-and-Charger-PBLTS01K/319830447' },
        'Ryobi PBLTS01B': { power: '18V Brushless', voltage: '18V', weight: '~30 lbs', buyUrl: 'https://www.homedepot.com/p/RYOBI-ONE-HP-18V-Brushless-Cordless-8-1-4-in-Compact-Portable-Jobsite-Table-Saw-Tool-Only-PBLTS01B/319830446' },
        'Craftsman CMXETAX69434510': { power: '13A', voltage: '120V', weight: '~38 lbs', buyUrl: 'https://www.craftsman.com/en-us/product/cmxetax69434510/craftsman-8-14-inch-corded-electric-table-saw-13-amp' },
        'Craftsman CMXETAX69434502': { power: '15A', voltage: '120V', weight: '~55 lbs', buyUrl: 'https://www.craftsman.com/products/power-tools/saws/table-saws/cmxetax69434502--10-in-table-saw' },
        'Craftsman CMXETAX69434506': { power: '15A', voltage: '120V', weight: '~58 lbs', buyUrl: 'https://www.craftsman.com/en-us/product/cmxetax69434506/10-corded-electric-portable-table-saw-folding-stand-15-amp' },
        'JET JPS-10-30': { power: '1.75 HP', voltage: '115V', weight: '~276 lbs', buyUrl: 'https://jettools.com/jps-10-proshop-ii-10-inch-table-saw-cast-wings-30-inch-rip-1-3-4-hp-1ph-120v' },
        'JET JPS-10-52': { power: '1.75 HP', voltage: '115V', weight: '~286 lbs', buyUrl: 'https://jettools.com/jps-10-proshop-ii-10-inch-table-saw-steel-wings-extension-table-52-inch-rip-1ph-115v' },
        'JET JTAS-10XL30-DX': { power: '3 HP', voltage: '230V', weight: '~490 lbs', buyUrl: 'https://jettools.com/deluxe-xactar-saw-3hp-1ph-30-rip' },
        'JET JTAS-10XL50-1DX': { power: '3 HP', voltage: '230V', weight: '~510 lbs', buyUrl: 'https://jettools.com/deluxe-xactar-saw-3hp-1ph-50-rip' },
        'JET JTAS-10XL50-5/1DX': { power: '5 HP', voltage: '230V', weight: '~510 lbs', buyUrl: 'https://jettools.com/xacta-deluxe-10-inch-cabinet-saw-50-inch-rip-5hp-1ph-230v' },
        'JET JTAS-12-DX': { power: '5 HP', voltage: '230V', weight: '~623 lbs', buyUrl: 'https://www.jettools.com/us/en/p/jtas-12-dx-12-xacta-saw-5hp-1ph/708546PK' },
        'Laguna F1': { power: '1.5 HP', voltage: '110V', weight: '~195 lbs', buyUrl: 'https://lagunatools.com/classic/tablesaws/f1/' },
        'Laguna F2': { power: '1.75 HP', voltage: '110V', weight: '~276 lbs', buyUrl: 'https://lagunatools.com/classic/tablesaws/f2/' },
        'Laguna F3': { power: '3 HP', voltage: '220V', weight: '~385 lbs', buyUrl: 'https://lagunatools.com/classic/tablesaws/f3/' },
        'Laguna F3-52': { power: '3 HP', voltage: '220V', weight: '~405 lbs', buyUrl: 'https://lagunatools.com/classic/tablesaws/f3-52/' },
        'Shop Fox W1837': { power: '2 HP', voltage: '120V / 240V', weight: '~241 lbs', buyUrl: 'https://www.grizzly.com/products/shop-fox-10-2-hp-open-stand-hybrid-table-saw/w1837' },
        'Shop Fox W1888': { power: '2 HP', voltage: '115V / 230V', weight: '~403 lbs', buyUrl: 'https://www.northerntool.com/products/shop-fox-2-hp-10in-hybrid-table-saw-blade-diameter-10-horsepower-2-hp-volts-multi-model-w1888-5320695' },
        'Shop Fox W1819': { power: '3 HP', voltage: '230V', weight: '~539 lbs', buyUrl: 'https://www.northerntool.com/products/shop-fox-10in-table-saw-3-hp-230-volts-12-8-amps-1-phase-model-w1819-81191' },
        'Shop Fox W1851': { power: '2 HP', voltage: '110V / 220V', weight: '~410 lbs', buyUrl: 'https://www.northerntool.com/products/shop-fox-hybrid-cabinet-table-saw-2-hp-230-volts-16-amps-1-phase-model-w1851-81193' },
        'General Intl 350-3-36': { power: '3 HP', voltage: '230V', weight: '~490 lbs', buyUrl: 'https://www.acmetools.com/general-international-10in-right-tilt-commercial-3hp-1phase-table-saw-36in-rip-capacity-350-3-36/850018687768.html' },
        'General Intl 350-3-52': { power: '3 HP', voltage: '230V', weight: '~539 lbs', buyUrl: 'https://acmetools.com/general-international-10in-right-tilt-commercial-table-saw-3hp-1phase-52in-rip-capacity-350-3-52/850018687751.html' },
        'General Intl 850-3-52': { power: '3 HP', voltage: '230V', weight: '~576 lbs', buyUrl: 'https://www.acmetools.com/10in-auto-adjust-digital-table-saw-52in-rip-capacity-3hp-1-phase-850-3-52/850018687836.html' },
        'General Intl 850-5/3-36': { power: '5 HP', voltage: '230V / 460V (3-Phase)', weight: '~476 lbs', buyUrl: 'https://www.acmetools.com/general-international-10-auto-digital-table-saw-with-36-rip-capacity-5hp-3-phase-850-5-3-36/850018687867.html' },
        'Harvey HW110LC-36Pro': { power: '2 HP', voltage: '115V / 230V', weight: '~400 lbs', buyUrl: 'https://www.harveywoodworking.com/products/alpha-hw110lc-36pro-10-2hp-stain-less-cabinet-saw-with-big-eye-rip-fence' },
        'Harvey HW110TC-36Pro': { power: '3 HP', voltage: '230V', weight: '~510 lbs', buyUrl: 'https://www.harveywoodworking.com/products/alpha-hw110tc-36pro-52pro-10-3hp-stain-less-cabinet-saw-with-big-eye-rip-fence' },
        'Harvey HW110TC-52Pro': { power: '3 HP', voltage: '230V', weight: '~530 lbs', buyUrl: 'https://www.harveywoodworking.com/products/alpha-hw110tc-36pro-52pro-10-3hp-stain-less-cabinet-saw-with-big-eye-rip-fence' },
        'Harvey HW110S-36Pro': { power: '4 HP', voltage: '230V', weight: '~578 lbs', buyUrl: 'https://www.harveywoodworking.com/products/alpha-hw110s-36pro-52pro-10-4hp-stain-less-cabinet-saw-with-big-eye-rip-fence' },
        'Harvey HW110S-52Pro': { power: '4 HP', voltage: '230V', weight: '~600 lbs', buyUrl: 'https://www.harveywoodworking.com/products/alpha-hw110s-36pro-52pro-10-4hp-stain-less-cabinet-saw-with-big-eye-rip-fence' },
        'Metabo HPT C10RJS': { power: '15A', voltage: '120V', weight: '~96 lbs', buyUrl: 'https://www.metabo-hpt.com/products/product/c10rjs-10-jobsite-table-saw-w-fold-roll-stand-metabo-hpt' },
        'Metabo HPT C3610DRJQ4': { power: '36V MultiVolt', voltage: '36V / 120V (AC adapter)', weight: '~67 lbs', buyUrl: 'https://www.metabo-hpt.com/products/product/c3610drjq4-36v-multivolt-brushless-10-table-saw-tool-body-only' },
        'WEN TT1015': { power: '15A / 2 HP', voltage: '120V', weight: '~58 lbs', buyUrl: 'https://wenproducts.com/products/wen-tt1015-15-amp-2-hp-10-inch-industrial-benchtop-jobsite-table-saw' },
        'WEN TT0811': { power: '11A', voltage: '120V', weight: '~37.6 lbs', buyUrl: 'https://wenproducts.com/products/wen-tt0811-11-amp-8-25-inch-compact-benchtop-jobsite-table-saw' },
        'Porter-Cable PCB222TS': { power: '15A', voltage: '120V', weight: '~72.6 lbs', buyUrl: 'https://www.lowes.com/pd/PORTER-CABLE-10-in-Carbide-tipped-15-Amp-Table-Saw/50146380' },
        'Kobalt TS10302': { power: '15A', voltage: '120V', weight: '~70 lbs', buyUrl: 'https://www.lowes.com/pd/Kobalt-10-in-15-Amp-Portable-Jobsite-Table-Saw-with-Folding-Stand/5013569451' },
        'Kobalt TS10601': { power: '15A', voltage: '120V', weight: '~93 lbs', buyUrl: 'https://www.lowes.com/pd/Kobalt-10-in-15-Amp-Portable-Jobsite-Table-Saw-with-Gravity-Rise-Stand/5013569453' },
        'Kobalt TS10602': { power: '15A', voltage: '120V', weight: '~54 lbs', buyUrl: 'https://www.lowes.com/pd/Kobalt-10-in-15-Amp-Portable-Benchtop-Table-Saw/5013763383' },
        'Oliver 10040': { power: '1.75 HP', voltage: '115V / 220V', weight: '~275 lbs', buyUrl: 'https://olivermachinery.net/10-hybrid-table-saw-1' },
        'Oliver 4016': { power: '5 HP', voltage: '220V', weight: '~480 lbs', buyUrl: 'https://olivermachinery.net/10-table-saw-4016-003' },
        'Oliver 4045': { power: '7.5 HP / 3-phase', voltage: '220V / 440V', weight: '~550 lbs', buyUrl: 'https://olivermachinery.net/12-table-saw-4' },
        'Oliver 4065.002': { power: '7.5 HP / 3-phase', voltage: '220V / 440V', weight: '~814 lbs', buyUrl: 'https://olivermachinery.net/14-table-saw' },
        'Oliver 4065.003': { power: '10 HP / 3-phase', voltage: '220V / 440V', weight: '~814 lbs', buyUrl: 'https://olivermachinery.net/16-table-saw' },
        'Robland SZ250': { power: '4 HP', voltage: '230V / 400V (3-Phase)', weight: '~350 lbs', buyUrl: 'https://www.robland.com/shop/sz250-78' },
        'Robland M500': { power: '12.5 HP / 3-phase', voltage: '400V / 3-phase', weight: '~1,210 lbs', buyUrl: 'https://www.robland.com/shop/m500-m-el-79' },
        'Robland Z400': { power: '9.5 HP / 3-phase', voltage: '400V / 3-phase', weight: '~1,870 lbs', buyUrl: 'https://www.robland.com/shop/z400-m-el-74' },
        'Minimax SC 2C': { power: '5.5 HP', voltage: '230V', weight: '~925 lbs', buyUrl: 'https://www.scmgroup.com/en_US/scmwood/products/joinery-machines.c884/sliding-table-saws.896/minimax-sc-2g.706' },
        'Minimax SC 3C': { power: '4.8 HP', voltage: '230V / 3-phase', weight: '~683 lbs', buyUrl: 'https://www.scmgroup.com/en_US/scmwood/products/joinery-machines.c884/sliding-table-saws.896/minimax-sc-3g.746' },
        'Minimax SC 4E': { power: '4.8 HP', voltage: '230V / 3-phase', weight: '~1,014 lbs', buyUrl: 'https://www.scmgroup.com/en_US/scmwood/products/joinery-machines.c884/sliding-table-saws.896/minimax-sc-4e.196042' },
        'Hammer K2S': { power: '2.5 HP', voltage: '230V', weight: '~440 lbs', buyUrl: 'https://www.felder-group.com/en-us/shop/sliding-table-saws-sc1782190/hammer-k2s-sliding-table-saw-sp3947015' },
        'Hammer K3 Winner': { power: '4 HP', voltage: '230V', weight: '~617 lbs', buyUrl: 'https://www.felder-group.com/en-us/shop/sliding-table-saws-sc1782190/hammer-k3-winner-sliding-table-saw-sp986264' },
        'Hammer K430': { power: '7.5 HP / 3-phase', voltage: '230V / 3-phase', weight: '~800 lbs', buyUrl: 'https://www.felder-group.com/en-us/shop/sliding-table-saws-sc1782190/hammer-sliding-table-saw-k-430-3x230v-60hz-ce-csa-sp4890978' },
        'Felder K700 Professional': { power: '5.5 HP / 3-phase', voltage: '230V / 3-phase', weight: '~1,232 lbs', buyUrl: 'https://www.felder-group.com/en-us/products/sliding-table-saws-c1947/sliding-table-panel-saw-k-700-p4129583' },

        // Table Saws -- deeper pass on already-represented manufacturers (2026-08-09): their
        // full current lineups run well past the one model each originally researched.
        'SawStop CTS-120A60': { power: '15A', voltage: '120V', weight: '~68 lbs', buyUrl: 'https://www.sawstop.com/product/compact-table-saw/' },
        'SawStop CNS175-TGP236': { power: '1.75 HP', voltage: '120V (240V convertible)', weight: '~310 lbs', buyUrl: 'https://www.sawstop.com/product/contractor-saw-cns175-tgp236/' },
        'SawStop PCS175-TGP236': { power: '1.75 HP', voltage: '120V (240V convertible)', weight: '~367 lbs', buyUrl: 'https://www.sawstop.com/product/professional-cabinet-saw-pcs175-tgp236/' },
        'SawStop PCS31230-TGP236': { power: '3 HP', voltage: '220V', weight: '~449 lbs', buyUrl: 'https://www.sawstop.com/product/professional-cabinet-saw-pcs31230-tgp236/' },
        'SawStop ICS51230-36': { power: '5 HP', voltage: '230V (1-phase)', weight: '~635 lbs', buyUrl: 'https://www.sawstop.com/product/industrial-cabinet-saw-ics51230-36/' },
        'SawStop ICS53230-TGI236': { power: '5 HP', voltage: '230V (3-phase)', weight: '~635 lbs', buyUrl: 'https://www.sawstop.com/product/industrial-cabinet-saw-ics53230-tgi236/' },
        'SawStop ICS73230-TGI236': { power: '7.5 HP', voltage: '230V (3-phase)', weight: '~650 lbs', buyUrl: 'https://www.sawstop.com/product/industrial-cabinet-saw-ics73230-tgi236/' },
        'Delta S36-295T3': { power: '15A', voltage: '120V', weight: '~61 lbs', buyUrl: 'https://deltamachinery.com/product/s36-295-t3-10-in-portable-table-saw/' },
        'Delta 36-6013': { power: '15A', voltage: '120V', weight: '~65 lbs', buyUrl: 'https://deltamachinery.com/product/36-6013-10-portable-job-site-table-saw/' },
        'Delta 36-5000T2': { power: '15A', voltage: '120V', weight: '~195 lbs', buyUrl: 'https://deltamachinery.com/product/36-5000t2-10-contractor-table-saw/' },
        'Delta 36-5100T2': { power: '15A', voltage: '120V', weight: '~234 lbs', buyUrl: 'https://deltamachinery.com/product/36-5100t2-10-contractor-table-saw/' },
        'Delta 36-725T2': { power: '15A', voltage: '120V', weight: '~220 lbs', buyUrl: 'https://deltamachinery.com/product/36-725t2-15-amp-10-in-table-saw/' },
        'DeWalt DWE7485': { power: '15A', voltage: '120V', weight: '~46 lbs', buyUrl: 'https://www.dewalt.com/en-us/product/dwe7485/15-amp-8-14-compact-portable-jobsite-table-saw' },
        'DeWalt DWE7491X': { power: '15A', voltage: '120V', weight: '~87 lbs', buyUrl: 'https://www.dewalt.com/en-us/product/dwe7491x/10-table-saw-scissor-stand' },
        'DeWalt DCS7485T1': { power: '60V MAX FlexVolt', voltage: '60V', weight: '~48 lbs', buyUrl: 'https://www.dewalt.com/en-us/product/dcs7485t1/60v-max-table-saw-kit' },
        'Grizzly G0771Z': { power: '2 HP', voltage: '120V', weight: '~324 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-10-2-hp-120v-hybrid-table-saw-w-t-shaped-fence/g0771z' },
        'Grizzly G0962': { power: '2 HP', voltage: '120V', weight: '~243 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-10-2-hp-open-stand-hybrid-table-saw/g0962' },
        'Grizzly G0899': { power: '2 HP', voltage: '115V / 230V', weight: '~450 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-10-2-hp-115v-230v-cabinet-saw/g0899' },
        'Grizzly G0651': { power: '3 HP', voltage: '220V', weight: '~602 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-10-3-hp-220v-heavy-duty-cabinet-table-saw/g0651' },
        'Grizzly G1023RL': { power: '3 HP', voltage: '240V', weight: '~490 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-10-3-hp-240v-cabinet-table-saw/g1023rl' },
        'Grizzly G1023RLX': { power: '3 HP', voltage: '240V', weight: '~522 lbs', buyUrl: 'https://www.grizzly.com/products/grizzly-10-3-hp-240v-cabinet-table-saw-with-7-rails/g1023rlx' },
        'Powermatic 1791001K': { power: '1.75 HP', voltage: '115V / 230V', weight: '~465 lbs', buyUrl: 'https://www.homedepot.com/p/Powermatic-PM1000-115-Volt-1-3-4-HP-1PH-Table-Saw-with-52-in-Accu-Fence-System-1791001K/308567961' },
        'Powermatic PM23150K': { power: '3 HP', voltage: '230V', weight: '~500 lbs', buyUrl: 'https://www.powermatic.com/us/en/p/2000b-table-saw-3hp-1ph-230v-50-rip-w-accu-fence/PM23150K' },
        'Powermatic PM25130K': { power: '5 HP', voltage: '230V', weight: '~490 lbs', buyUrl: 'https://www.powermatic.com/us/en/p/2000b-table-saw-5hp-1ph-230v-30-rip-w-accu-fence/PM25130K' },
        'Powermatic PM375350K': { power: '7.5 HP', voltage: '230V / 460V (3-phase)', weight: '~738 lbs', buyUrl: 'https://www.powermatic.com/pm375350k' },

        // Table Saws -- Rikon and King Canada (2026-08-09). Harbor Freight's BAUER brand
        // sells zero table saws (confirmed against harborfreight.com/brands/bauer) -- excluded.
        'Rikon 10-205': { power: '1-3/4 HP (15A/7.5A)', voltage: '120/240V', weight: '~260 lbs', buyUrl: 'https://rikontools.com/product/model-10-205-10-contractor-saw/' },
        'King Canada KC-10HCX': { power: '1.75 HP (15A@120V / 7.5A@240V)', voltage: '120V/240V', weight: '~236 lbs', buyUrl: 'https://www.kingcanada.com/en/products/woodworking/table-saws/kc-10hcx-10-cabinet-table-saw' },
        'King Canada KC-5100NS': { power: '15A', voltage: '120V', weight: '~70 lbs', buyUrl: 'https://www.kingcanada.com/en/products/woodworking/table-saws/kc-5100ns-10-jobsite-saw-with-folding-stand' },
        'King Canada KC-5016C': { power: '15A', voltage: '120V', weight: '~65 lbs', buyUrl: 'https://www.kingcanada.com/en/products/woodworking/table-saws/kc-5016c-10-portable-jobsite-table-saw' },
        'King Canada KC-5006R': { power: '15A', voltage: '120V', weight: '~48 lbs', buyUrl: 'https://www.kingcanada.com/en/products/woodworking/table-saws/kc-5006r-10-table-saw-with-riving-knife' }
    };

    // { name, category, layer, widthFt, lengthFt, heightFt } for every non-cabinet catalog
    // item (cabinets are built via a form, not this static list). widthFt/lengthFt/heightFt
    // mirror each catalog chip's data-width/data-length/data-height in workshop-planner.html.
    window.CATALOG_ITEMS = [
        { name: 'SawStop PCS175', category: 'Table Saws', layer: 'tools', widthFt: 3, lengthFt: 5.2, heightFt: 2.9 },
        { name: 'SawStop ICS', category: 'Table Saws', layer: 'tools', widthFt: 3.2, lengthFt: 5.5, heightFt: 3.0 },
        { name: 'Delta 36-L352', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 5.0, heightFt: 2.9 },
        { name: 'Laguna 14BX', category: 'Bandsaws', layer: 'tools', widthFt: 2.1, lengthFt: 2.5, heightFt: 5.8 },
        { name: 'Rikon 10-326', category: 'Bandsaws', layer: 'tools', widthFt: 2.3, lengthFt: 2.8, heightFt: 5.9 },
        { name: 'Grizzly G0513X2', category: 'Bandsaws', layer: 'tools', widthFt: 2.2, lengthFt: 2.6, heightFt: 5.9 },
        { name: 'Shop Fox W1706', category: 'Bandsaws', layer: 'tools', widthFt: 1.5, lengthFt: 1.3, heightFt: 5.8 },
        { name: 'Shop Fox W1729', category: 'Bandsaws', layer: 'tools', widthFt: 3.0, lengthFt: 2.7, heightFt: 6.3 },
        { name: 'Shop Fox W1825', category: 'Bandsaws', layer: 'tools', widthFt: 3.0, lengthFt: 2.7, heightFt: 6.3 },
        { name: 'Shop Fox W1849', category: 'Bandsaws', layer: 'tools', widthFt: 1.8, lengthFt: 1.3, heightFt: 6.0 },
        { name: 'Shop Fox W1878', category: 'Bandsaws', layer: 'tools', widthFt: 0.5, lengthFt: 1.3, heightFt: 2.5 },
        { name: 'Harvey Ambassador C14Pro', category: 'Bandsaws', layer: 'tools', widthFt: 2.0, lengthFt: 1.3, heightFt: 5.9 },
        { name: 'Harvey Alpha HW615Pro', category: 'Bandsaws', layer: 'tools', widthFt: 2.1, lengthFt: 1.5, heightFt: 6.0 },
        { name: 'Harvey Alpha A-15', category: 'Bandsaws', layer: 'tools', widthFt: 2.4, lengthFt: 1.6, heightFt: 6.4 },
        { name: 'Minimax S 45N', category: 'Bandsaws', layer: 'tools', widthFt: 2.8, lengthFt: 2.6, heightFt: 6.1 },
        { name: 'Minimax S 440P', category: 'Bandsaws', layer: 'tools', widthFt: 2.7, lengthFt: 2.2, heightFt: 6.5 },
        { name: 'Minimax S 540P', category: 'Bandsaws', layer: 'tools', widthFt: 3.1, lengthFt: 2.6, heightFt: 7.1 },
        { name: 'Minimax S 640P', category: 'Bandsaws', layer: 'tools', widthFt: 2.4, lengthFt: 4.0, heightFt: 7.8 },
        { name: 'Powermatic PWBS-14CS', category: 'Bandsaws', layer: 'tools', widthFt: 2.8, lengthFt: 1.7, heightFt: 5.7 },
        { name: 'Powermatic PM1500', category: 'Bandsaws', layer: 'tools', widthFt: 2.9, lengthFt: 2.5, heightFt: 6.7 },
        { name: 'Powermatic PM1800BT', category: 'Bandsaws', layer: 'tools', widthFt: 3.5, lengthFt: 3.3, heightFt: 6.8 },
        { name: 'Powermatic PM2013B', category: 'Bandsaws', layer: 'tools', widthFt: 3.5, lengthFt: 3.3, heightFt: 6.8 },
        { name: 'Powermatic PM2415B', category: 'Bandsaws', layer: 'tools', widthFt: 3.5, lengthFt: 3.7, heightFt: 6.8 },
        { name: 'JET JWB-10', category: 'Bandsaws', layer: 'tools', widthFt: 1.6, lengthFt: 2.5, heightFt: 5.0 },
        { name: 'JET JWBS-14CS', category: 'Bandsaws', layer: 'tools', widthFt: 2.2, lengthFt: 1.6, heightFt: 5.7 },
        { name: 'JET JWBS-14SFX', category: 'Bandsaws', layer: 'tools', widthFt: 2.3, lengthFt: 3.1, heightFt: 6.3 },
        { name: 'JET JWBS-15', category: 'Bandsaws', layer: 'tools', widthFt: 2.7, lengthFt: 2.5, heightFt: 6.2 },
        { name: 'JET JWBS-18SFX', category: 'Bandsaws', layer: 'tools', widthFt: 3.2, lengthFt: 2.7, heightFt: 6.6 },
        { name: 'JET JWBS-20-5', category: 'Bandsaws', layer: 'tools', widthFt: 2.7, lengthFt: 3.1, heightFt: 7.3 },
        { name: 'Delta 28-400', category: 'Bandsaws', layer: 'tools', widthFt: 1.6, lengthFt: 2.3, heightFt: 5.5 },
        { name: 'Powermatic PJ882', category: 'Jointers & Planers', layer: 'tools', widthFt: 1.4, lengthFt: 7.3, heightFt: 3.0 },
        { name: 'Powermatic 201HH', category: 'Jointers & Planers', layer: 'tools', widthFt: 2.6, lengthFt: 3.4, heightFt: 3.2 },
        { name: 'Hammer A3-31', category: 'Jointers & Planers', layer: 'tools', widthFt: 2.5, lengthFt: 4.0, heightFt: 3.0 },
        { name: 'Grizzly G0771Z', category: 'Sanding', layer: 'tools', widthFt: 1.8, lengthFt: 2.2, heightFt: 5.0 },
        { name: 'JET 22-44 Sander', category: 'Sanding', layer: 'tools', widthFt: 1.5, lengthFt: 1.5, heightFt: 3.3 },
        { name: 'SuperMax 19-38', category: 'Sanding', layer: 'tools', widthFt: 2.0, lengthFt: 3.5, heightFt: 4.0 },
        { name: 'Powermatic PM2800B', category: 'Drilling & Boring', layer: 'tools', widthFt: 2.0, lengthFt: 2.3, heightFt: 6.3 },
        { name: 'General 75-510 M1', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.8, lengthFt: 2.0, heightFt: 5.5 },
        { name: 'Powermatic 3520C', category: 'Turning', layer: 'tools', widthFt: 2.0, lengthFt: 6.5, heightFt: 4.0 },
        { name: 'JET JWL-1640EVS', category: 'Turning', layer: 'tools', widthFt: 1.8, lengthFt: 5.8, heightFt: 3.7 },
        { name: 'SawStop RT', category: 'Routing', layer: 'tools', widthFt: 2.0, lengthFt: 3.0, heightFt: 3.0 },
        { name: 'Kreg PRS2100', category: 'Routing', layer: 'tools', widthFt: 1.8, lengthFt: 2.8, heightFt: 3.0 },
        { name: 'Festool Kapex KS 120', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.5, lengthFt: 4.5, heightFt: 3.7 },
        { name: 'Bosch GTS1041A', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.2, lengthFt: 4.0, heightFt: 3.8 },
        { name: 'JET DC-1100VX', category: 'Dust Collection', layer: 'dust-collection', widthFt: 2.2, lengthFt: 2.2, heightFt: 7.2 },
        { name: 'Oneida Super Dust Deputy XL', category: 'Dust Collection', layer: 'dust-collection', widthFt: 1.5, lengthFt: 1.5, heightFt: 2.8 },
        { name: '4in Dust Duct 2ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 2.0, heightFt: 7.0 },
        { name: '4in Dust Duct 4ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 4.0, heightFt: 7.0 },
        { name: '4in Dust Duct 6ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 6.0, heightFt: 7.0 },
        { name: '4in Dust Duct 8ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 8.0, heightFt: 7.0 },
        { name: '4in Dust Duct 10ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 10.0, heightFt: 7.0 },
        { name: '4in Dust Duct Custom', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 5.0, heightFt: 7.0 },
        { name: '4in Duct Elbow', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.6, lengthFt: 0.6, heightFt: 7.0 },
        { name: '4in Duct Y-Joint', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.7, lengthFt: 0.7, heightFt: 7.0 },
        { name: '4in Duct T-Joint', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.7, lengthFt: 0.7, heightFt: 7.0 },
        { name: '4in Pipe Bracket', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 0.15, heightFt: 7.0 },
        { name: 'Blast Gate', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 0.5, heightFt: 7.0 },
        { name: '4in Duct Drop', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.35, lengthFt: 0.5, heightFt: 5.0 },
        { name: '6in Dust Duct 2ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 2.0, heightFt: 7.0 },
        { name: '6in Dust Duct 4ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 4.0, heightFt: 7.0 },
        { name: '6in Dust Duct 6ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 6.0, heightFt: 7.0 },
        { name: '6in Dust Duct 8ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 8.0, heightFt: 7.0 },
        { name: '6in Dust Duct 10ft', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 10.0, heightFt: 7.0 },
        { name: '6in Dust Duct Custom', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 5.0, heightFt: 7.0 },
        { name: '6in Duct Elbow', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.8, lengthFt: 0.8, heightFt: 7.0 },
        { name: '6in Duct Y-Joint', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.9, lengthFt: 0.9, heightFt: 7.0 },
        { name: '6in Duct T-Joint', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.9, lengthFt: 0.9, heightFt: 7.0 },
        { name: '6in Pipe Bracket', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.7, lengthFt: 0.15, heightFt: 7.0 },
        { name: '6in Blast Gate', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 0.6, heightFt: 7.0 },
        { name: '6in Duct Drop', category: 'Dust Collection', layer: 'dust-collection', widthFt: 0.5, lengthFt: 0.6, heightFt: 5.0 },
        { name: 'LED Shop Light 4ft', category: 'Lighting', layer: 'lighting', widthFt: 0.4, lengthFt: 4.0, heightFt: 8.5 },
        { name: 'High Bay LED Fixture', category: 'Lighting', layer: 'lighting', widthFt: 1.2, lengthFt: 1.2, heightFt: 9.0 },
        { name: 'Adjustable Task Light', category: 'Lighting', layer: 'lighting', widthFt: 0.6, lengthFt: 0.6, heightFt: 5.5 },
        { name: 'Shapeoko Pro XXL', category: 'CNC & Digital Fab', layer: 'tools', widthFt: 3.0, lengthFt: 4.5, heightFt: 1.2 },
        { name: 'Glowforge Pro', category: 'CNC & Digital Fab', layer: 'tools', widthFt: 1.6, lengthFt: 2.8, heightFt: 0.7 },
        { name: 'Bambu Lab X1 Carbon', category: 'CNC & Digital Fab', layer: 'tools', widthFt: 1.3, lengthFt: 1.3, heightFt: 1.5 },
        { name: 'Prusa MK4', category: 'CNC & Digital Fab', layer: 'tools', widthFt: 1.5, lengthFt: 1.6, heightFt: 1.3 },
        { name: 'Creality K1 Max', category: 'CNC & Digital Fab', layer: 'tools', widthFt: 1.8, lengthFt: 2.0, heightFt: 1.6 },
        { name: 'Elegoo Saturn 4 Ultra', category: 'CNC & Digital Fab', layer: 'tools', widthFt: 0.8, lengthFt: 0.9, heightFt: 1.6 },
        { name: 'Assembly Table', category: 'Assembly & Storage', layer: 'tools', widthFt: 3.0, lengthFt: 6.0, heightFt: 3.0 },
        { name: 'Kreg Mobile Project Center', category: 'Assembly & Storage', layer: 'tools', widthFt: 2.0, lengthFt: 3.0, heightFt: 3.0 },
        { name: 'Milwaukee PACKOUT Rolling Box', category: 'Tool Storage', layer: 'tools', widthFt: 1.8, lengthFt: 1.3, heightFt: 1.3 },
        { name: 'DEWALT TOUGHSYSTEM 2.0', category: 'Tool Storage', layer: 'tools', widthFt: 2.0, lengthFt: 1.8, heightFt: 1.7 },
        { name: 'Craftsman 26in Rolling Cabinet', category: 'Tool Storage', layer: 'tools', widthFt: 2.2, lengthFt: 1.5, heightFt: 3.2 },
        { name: 'Kobalt 41in Rolling Chest', category: 'Tool Storage', layer: 'tools', widthFt: 3.4, lengthFt: 1.5, heightFt: 3.0 },
        { name: 'US General 56in Roller Cabinet', category: 'Tool Storage', layer: 'tools', widthFt: 4.7, lengthFt: 1.8, heightFt: 3.1 },
        { name: 'Husky 52in Mobile Workbench', category: 'Tool Storage', layer: 'tools', widthFt: 4.3, lengthFt: 2.1, heightFt: 3.3 },
        { name: 'Snap-on KRL1023 Classic 78', category: 'Tool Storage', layer: 'tools', widthFt: 6.5, lengthFt: 2.1, heightFt: 3.5 },
        { name: 'Husky 72in Tool Chest Combo', category: 'Tool Storage', layer: 'tools', widthFt: 2.0, lengthFt: 6.0, heightFt: 6.2 },

        // Researched 2026-07-18 catalog expansion — see TOOL_SPECS entries above for buyUrl/specs
        { name: 'DeWalt DWE7491RS', category: 'Table Saws', layer: 'tools', widthFt: 2.2, lengthFt: 2.2, heightFt: 2.9 },
        { name: 'SKIL TS6307-00', category: 'Table Saws', layer: 'tools', widthFt: 2.0, lengthFt: 2.2, heightFt: 2.7 },
        { name: 'RIDGID R4518', category: 'Table Saws', layer: 'tools', widthFt: 2.4, lengthFt: 2.4, heightFt: 2.8 },
        { name: 'Grizzly G0715P', category: 'Table Saws', layer: 'tools', widthFt: 1.7, lengthFt: 1.8, heightFt: 3.3 },
        { name: 'Powermatic PM1000', category: 'Table Saws', layer: 'tools', widthFt: 3.6, lengthFt: 5.1, heightFt: 3.7 },
        { name: 'Grizzly G0690', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.2, heightFt: 3.3 },
        { name: 'Bosch 4100XC-10', category: 'Table Saws', layer: 'tools', widthFt: 2.3, lengthFt: 2.7, heightFt: 2.9 },
        { name: 'Bosch GTS15-10', category: 'Table Saws', layer: 'tools', widthFt: 2.3, lengthFt: 2.3, heightFt: 2.9 },
        { name: 'Bosch GTS18V-08N', category: 'Table Saws', layer: 'tools', widthFt: 2.0, lengthFt: 2.0, heightFt: 1.4 },
        { name: 'Bosch GTS18V-08N14', category: 'Table Saws', layer: 'tools', widthFt: 2.0, lengthFt: 2.0, heightFt: 1.4 },
        { name: 'Milwaukee 2736-20', category: 'Table Saws', layer: 'tools', widthFt: 1.9, lengthFt: 1.8, heightFt: 1.3 },
        { name: 'Milwaukee 2736-21HD', category: 'Table Saws', layer: 'tools', widthFt: 1.9, lengthFt: 1.8, heightFt: 1.3 },
        { name: 'Ryobi RTS23', category: 'Table Saws', layer: 'tools', widthFt: 2.3, lengthFt: 2.5, heightFt: 2.9 },
        { name: 'Ryobi RTS12', category: 'Table Saws', layer: 'tools', widthFt: 2.2, lengthFt: 2.3, heightFt: 2.8 },
        { name: 'Ryobi RTS08', category: 'Table Saws', layer: 'tools', widthFt: 1.6, lengthFt: 2.3, heightFt: 1.1 },
        { name: 'Ryobi PBLTS01K', category: 'Table Saws', layer: 'tools', widthFt: 1.8, lengthFt: 1.9, heightFt: 1.3 },
        { name: 'Ryobi PBLTS01B', category: 'Table Saws', layer: 'tools', widthFt: 1.8, lengthFt: 1.9, heightFt: 1.3 },
        { name: 'Craftsman CMXETAX69434510', category: 'Table Saws', layer: 'tools', widthFt: 1.8, lengthFt: 2.0, heightFt: 1.3 },
        { name: 'Craftsman CMXETAX69434502', category: 'Table Saws', layer: 'tools', widthFt: 2.3, lengthFt: 1.8, heightFt: 2.8 },
        { name: 'Craftsman CMXETAX69434506', category: 'Table Saws', layer: 'tools', widthFt: 2.3, lengthFt: 1.8, heightFt: 2.8 },
        { name: 'JET JPS-10-30', category: 'Table Saws', layer: 'tools', widthFt: 2.7, lengthFt: 5.0, heightFt: 2.9 },
        { name: 'JET JPS-10-52', category: 'Table Saws', layer: 'tools', widthFt: 2.8, lengthFt: 7.1, heightFt: 2.9 },
        { name: 'JET JTAS-10XL30-DX', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 5.3, heightFt: 3.0 },
        { name: 'JET JTAS-10XL50-1DX', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 6.9, heightFt: 3.0 },
        { name: 'JET JTAS-10XL50-5/1DX', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 6.9, heightFt: 3.0 },
        { name: 'JET JTAS-12-DX', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 7.5, heightFt: 3.2 },
        { name: 'Laguna F1', category: 'Table Saws', layer: 'tools', widthFt: 3.1, lengthFt: 4.9, heightFt: 2.9 },
        { name: 'Laguna F2', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.6, heightFt: 3.6 },
        { name: 'Laguna F3', category: 'Table Saws', layer: 'tools', widthFt: 4.7, lengthFt: 5.8, heightFt: 3.6 },
        { name: 'Laguna F3-52', category: 'Table Saws', layer: 'tools', widthFt: 4.7, lengthFt: 7.1, heightFt: 3.6 },
        { name: 'Shop Fox W1837', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.3, heightFt: 3.0 },
        { name: 'Shop Fox W1888', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.5, heightFt: 4.0 },
        { name: 'Shop Fox W1819', category: 'Table Saws', layer: 'tools', widthFt: 3.8, lengthFt: 5.2, heightFt: 3.3 },
        { name: 'Shop Fox W1851', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.7, heightFt: 4.0 },
        { name: 'General Intl 350-3-36', category: 'Table Saws', layer: 'tools', widthFt: 2.8, lengthFt: 5.8, heightFt: 2.8 },
        { name: 'General Intl 350-3-52', category: 'Table Saws', layer: 'tools', widthFt: 2.8, lengthFt: 7.1, heightFt: 2.8 },
        { name: 'General Intl 850-3-52', category: 'Table Saws', layer: 'tools', widthFt: 2.9, lengthFt: 7.1, heightFt: 2.8 },
        { name: 'General Intl 850-5/3-36', category: 'Table Saws', layer: 'tools', widthFt: 2.9, lengthFt: 5.8, heightFt: 2.8 },
        { name: 'Harvey HW110LC-36Pro', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.8, heightFt: 4.0 },
        { name: 'Harvey HW110TC-36Pro', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.8, heightFt: 4.0 },
        { name: 'Harvey HW110TC-52Pro', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 7.1, heightFt: 4.0 },
        { name: 'Harvey HW110S-36Pro', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.8, heightFt: 4.0 },
        { name: 'Harvey HW110S-52Pro', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 7.1, heightFt: 4.0 },
        { name: 'Metabo HPT C10RJS', category: 'Table Saws', layer: 'tools', widthFt: 2.3, lengthFt: 2.3, heightFt: 2.9 },
        { name: 'Metabo HPT C3610DRJQ4', category: 'Table Saws', layer: 'tools', widthFt: 2.3, lengthFt: 2.3, heightFt: 2.9 },
        { name: 'WEN TT1015', category: 'Table Saws', layer: 'tools', widthFt: 1.7, lengthFt: 2.2, heightFt: 1.4 },
        { name: 'WEN TT0811', category: 'Table Saws', layer: 'tools', widthFt: 1.25, lengthFt: 1.9, heightFt: 1.1 },
        { name: 'Porter-Cable PCB222TS', category: 'Table Saws', layer: 'tools', widthFt: 2.2, lengthFt: 2.2, heightFt: 2.8 },
        { name: 'Kobalt TS10302', category: 'Table Saws', layer: 'tools', widthFt: 2.5, lengthFt: 3.8, heightFt: 2.9 },
        { name: 'Kobalt TS10601', category: 'Table Saws', layer: 'tools', widthFt: 2.6, lengthFt: 4.0, heightFt: 3.0 },
        { name: 'Kobalt TS10602', category: 'Table Saws', layer: 'tools', widthFt: 2.2, lengthFt: 2.5, heightFt: 1.3 },
        { name: 'Oliver 10040', category: 'Table Saws', layer: 'tools', widthFt: 2.7, lengthFt: 5.6, heightFt: 2.9 },
        { name: 'Oliver 4016', category: 'Table Saws', layer: 'tools', widthFt: 2.7, lengthFt: 6.0, heightFt: 3.3 },
        { name: 'Oliver 4045', category: 'Table Saws', layer: 'tools', widthFt: 3.8, lengthFt: 6.3, heightFt: 3.4 },
        { name: 'Oliver 4065.002', category: 'Table Saws', layer: 'tools', widthFt: 4.0, lengthFt: 6.8, heightFt: 3.7 },
        { name: 'Oliver 4065.003', category: 'Table Saws', layer: 'tools', widthFt: 4.0, lengthFt: 6.8, heightFt: 3.7 },
        { name: 'Robland SZ250', category: 'Table Saws', layer: 'tools', widthFt: 3.2, lengthFt: 5.2, heightFt: 3.0 },
        { name: 'Robland M500', category: 'Table Saws', layer: 'tools', widthFt: 4.5, lengthFt: 7.0, heightFt: 3.4 },
        { name: 'Robland Z400', category: 'Table Saws', layer: 'tools', widthFt: 4.5, lengthFt: 11.5, heightFt: 3.4 },
        { name: 'Minimax SC 2C', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 7.0, heightFt: 3.1 },
        { name: 'Minimax SC 3C', category: 'Table Saws', layer: 'tools', widthFt: 3.5, lengthFt: 8.0, heightFt: 3.1 },
        { name: 'Minimax SC 4E', category: 'Table Saws', layer: 'tools', widthFt: 3.6, lengthFt: 8.5, heightFt: 3.2 },
        { name: 'Hammer K2S', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 7.0, heightFt: 3.5 },
        { name: 'Hammer K3 Winner', category: 'Table Saws', layer: 'tools', widthFt: 3.2, lengthFt: 7.0, heightFt: 2.9 },
        { name: 'Hammer K430', category: 'Table Saws', layer: 'tools', widthFt: 5.5, lengthFt: 9.0, heightFt: 3.0 },
        { name: 'Felder K700 Professional', category: 'Table Saws', layer: 'tools', widthFt: 4.0, lengthFt: 9.0, heightFt: 3.0 },
        { name: 'SawStop CTS-120A60', category: 'Table Saws', layer: 'tools', widthFt: 2.0, lengthFt: 2.3, heightFt: 1.2 },
        { name: 'SawStop CNS175-TGP236', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.1, heightFt: 2.9 },
        { name: 'SawStop PCS175-TGP236', category: 'Table Saws', layer: 'tools', widthFt: 2.8, lengthFt: 5.8, heightFt: 2.8 },
        { name: 'SawStop PCS31230-TGP236', category: 'Table Saws', layer: 'tools', widthFt: 2.8, lengthFt: 5.8, heightFt: 2.8 },
        { name: 'SawStop ICS51230-36', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 5.8, heightFt: 2.8 },
        { name: 'SawStop ICS53230-TGI236', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 5.8, heightFt: 2.8 },
        { name: 'SawStop ICS73230-TGI236', category: 'Table Saws', layer: 'tools', widthFt: 3.0, lengthFt: 5.8, heightFt: 2.8 },
        { name: 'Delta S36-295T3', category: 'Table Saws', layer: 'tools', widthFt: 2.0, lengthFt: 3.8, heightFt: 3.0 },
        { name: 'Delta 36-6013', category: 'Table Saws', layer: 'tools', widthFt: 2.0, lengthFt: 3.8, heightFt: 3.0 },
        { name: 'Delta 36-5000T2', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.2, heightFt: 3.6 },
        { name: 'Delta 36-5100T2', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.2, heightFt: 3.6 },
        { name: 'Delta 36-725T2', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.3, heightFt: 2.9 },
        { name: 'DeWalt DWE7485', category: 'Table Saws', layer: 'tools', widthFt: 1.2, lengthFt: 1.9, heightFt: 1.1 },
        { name: 'DeWalt DWE7491X', category: 'Table Saws', layer: 'tools', widthFt: 2.2, lengthFt: 2.2, heightFt: 2.5 },
        { name: 'DeWalt DCS7485T1', category: 'Table Saws', layer: 'tools', widthFt: 2.0, lengthFt: 1.9, heightFt: 1.1 },
        { name: 'Grizzly G0771Z', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.3, heightFt: 3.0 },
        { name: 'Grizzly G0962', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 5.3, heightFt: 3.0 },
        { name: 'Grizzly G0899', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.5, heightFt: 4.0 },
        { name: 'Grizzly G0651', category: 'Table Saws', layer: 'tools', widthFt: 6.3, lengthFt: 7.6, heightFt: 3.4 },
        { name: 'Grizzly G1023RL', category: 'Table Saws', layer: 'tools', widthFt: 3.9, lengthFt: 5.5, heightFt: 3.3 },
        { name: 'Grizzly G1023RLX', category: 'Table Saws', layer: 'tools', widthFt: 3.9, lengthFt: 7.9, heightFt: 3.3 },
        { name: 'Powermatic 1791001K', category: 'Table Saws', layer: 'tools', widthFt: 3.6, lengthFt: 6.9, heightFt: 3.7 },
        { name: 'Powermatic PM23150K', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 7.1, heightFt: 3.4 },
        { name: 'Powermatic PM25130K', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.6, heightFt: 3.4 },
        { name: 'Powermatic PM375350K', category: 'Table Saws', layer: 'tools', widthFt: 3.4, lengthFt: 7.1, heightFt: 3.4 },
        { name: 'Rikon 10-205', category: 'Table Saws', layer: 'tools', widthFt: 4.3, lengthFt: 3.3, heightFt: 3.8 },
        { name: 'King Canada KC-10HCX', category: 'Table Saws', layer: 'tools', widthFt: 3.3, lengthFt: 5.1, heightFt: 3.5 },
        { name: 'King Canada KC-5100NS', category: 'Table Saws', layer: 'tools', widthFt: 2.5, lengthFt: 4.8, heightFt: 3.5 },
        { name: 'King Canada KC-5016C', category: 'Table Saws', layer: 'tools', widthFt: 2.1, lengthFt: 3.4, heightFt: 1.7 },
        { name: 'King Canada KC-5006R', category: 'Table Saws', layer: 'tools', widthFt: 2.4, lengthFt: 2.2, heightFt: 3.4 },
        { name: 'DeWalt DWS779', category: 'Crosscut & Miter', layer: 'tools', widthFt: 1.6, lengthFt: 2.7, heightFt: 1.9 },
        { name: 'Bosch GCM12SD', category: 'Crosscut & Miter', layer: 'tools', widthFt: 1.0, lengthFt: 1.9, heightFt: 1.6 },
        { name: 'Makita LS1019L', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.1, lengthFt: 2.6, heightFt: 2.2 },
        { name: 'Metabo HPT C10FCGS', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.0, lengthFt: 2.0, heightFt: 1.5 },
        { name: 'Milwaukee 2734-20', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.3, lengthFt: 8.3, heightFt: 4.1 },
        { name: 'Milwaukee 2739-21HD', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.3, lengthFt: 8.3, heightFt: 4.3 },
        { name: 'RIDGID R4222', category: 'Crosscut & Miter', layer: 'tools', widthFt: 1.9, lengthFt: 9.5, heightFt: 4.5 },
        { name: 'Craftsman CMXEMAX69434501', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.0, lengthFt: 9.5, heightFt: 4.3 },
        { name: 'Metabo HPT C12RSH2S', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.6, lengthFt: 8.0, heightFt: 4.7 },
        { name: 'Metabo HPT C3612DRAQ4', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.6, lengthFt: 8.0, heightFt: 4.7 },
        { name: 'Makita LS1219L', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.5, lengthFt: 8.4, heightFt: 4.5 },
        { name: 'Makita XSL08PT', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.5, lengthFt: 8.4, heightFt: 4.5 },
        { name: 'DeWalt DHS790AT2', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.1, lengthFt: 8.0, heightFt: 4.4 },
        { name: 'DeWalt DCS781X1', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.1, lengthFt: 8.0, heightFt: 4.4 },
        { name: 'Bosch GCM18V-12GDCN', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.3, lengthFt: 8.6, heightFt: 4.5 },
        { name: 'Festool KSC 60 EB-Basic', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.0, lengthFt: 7.9, heightFt: 5.0 },
        { name: 'Skilsaw SPT88-01', category: 'Crosscut & Miter', layer: 'tools', widthFt: 2.2, lengthFt: 2.9, heightFt: 2.3 },
        { name: 'Rikon 10-305', category: 'Bandsaws', layer: 'tools', widthFt: 1.1, lengthFt: 1.0, heightFt: 1.5 },
        { name: 'Grizzly G0555LX', category: 'Bandsaws', layer: 'tools', widthFt: 2.0, lengthFt: 1.4, heightFt: 5.6 },
        { name: 'DeWalt DW735X', category: 'Jointers & Planers', layer: 'tools', widthFt: 1.8, lengthFt: 2.0, heightFt: 1.8 },
        { name: 'JET JWJ-8CS', category: 'Jointers & Planers', layer: 'tools', widthFt: 0.75, lengthFt: 5.5, heightFt: 3.0 },
        { name: 'Cutech 40160HB', category: 'Jointers & Planers', layer: 'tools', widthFt: 0.6, lengthFt: 2.5, heightFt: 1.2 },
        { name: 'WEN 6502T', category: 'Sanding', layer: 'tools', widthFt: 1.5, lengthFt: 1.3, heightFt: 0.9 },
        { name: 'RIDGID EB4424', category: 'Sanding', layer: 'tools', widthFt: 1.5, lengthFt: 1.5, heightFt: 1.2 },
        { name: 'WEN 4210', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.6, lengthFt: 0.6, heightFt: 2.6 },
        { name: 'Powermatic PM701', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.3, lengthFt: 1.5, heightFt: 1.5 },
        { name: 'JET JDP-20S', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.1, lengthFt: 1.9, heightFt: 5.7 },
        { name: 'JET JDP-20MF', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.1, lengthFt: 1.9, heightFt: 5.7 },
        { name: 'JET JDP-17MF', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.6, lengthFt: 2.4, heightFt: 5.4 },
        { name: 'JET JDP-15B', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.4, lengthFt: 2.3, heightFt: 3.7 },
        { name: 'JET JWDP-12', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.8, lengthFt: 1.3, heightFt: 2.7 },
        { name: 'Grizzly G7948', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.5, lengthFt: 1.9, heightFt: 5.9 },
        { name: 'Grizzly G0784', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.5, lengthFt: 2.0, heightFt: 6.0 },
        { name: 'Grizzly G0925', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.7, lengthFt: 0.9, heightFt: 1.7 },
        { name: 'Grizzly T31739', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.9, lengthFt: 1.3, heightFt: 3.0 },
        { name: 'Grizzly G7945', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.7, lengthFt: 1.1, heightFt: 2.6 },
        { name: 'Shop Fox W1680', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.9, lengthFt: 1.5, heightFt: 5.5 },
        { name: 'Shop Fox M1039', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.5, lengthFt: 1.9, heightFt: 5.9 },
        { name: 'Shop Fox W1668', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.8, lengthFt: 1.2, heightFt: 3.2 },
        { name: 'Rikon 30-230', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.5, lengthFt: 1.9, heightFt: 5.4 },
        { name: 'Rikon 30-240', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.4, lengthFt: 1.9, heightFt: 5.7 },
        { name: 'Rikon 30-120', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.9, lengthFt: 1.5, heightFt: 2.7 },
        { name: 'Rikon 30-217', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.1, lengthFt: 1.7, heightFt: 5.8 },
        { name: 'Delta 18-900L', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.7, lengthFt: 2.3, heightFt: 5.8 },
        { name: 'NOVA Voyager DVR', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.5, lengthFt: 1.9, heightFt: 5.25 },
        { name: 'WEN 4208T', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.6, lengthFt: 0.9, heightFt: 1.9 },
        { name: 'WEN 4211', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.7, lengthFt: 1.1, heightFt: 2.2 },
        { name: 'WEN 4214T', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.1, lengthFt: 1.4, heightFt: 3.1 },
        { name: 'WEN 4225T', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.0, lengthFt: 2.1, heightFt: 5.25 },
        { name: 'WEN 4227T', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.2, lengthFt: 2.5, heightFt: 5.6 },
        { name: 'WEN 4233', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.3, lengthFt: 3.2, heightFt: 2.75 },
        { name: 'General Intl 75-155 M1', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.9, lengthFt: 1.4, heightFt: 5.3 },
        { name: 'General Intl 75-260 M1', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.0, lengthFt: 1.6, heightFt: 5.4 },
        { name: 'General Intl 75-500 M1', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.7, lengthFt: 2.0, heightFt: 5.8 },
        { name: 'General Intl 75-710 M1', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.0, lengthFt: 1.6, heightFt: 5.4 },
        { name: 'Craftsman CMXEDAX69434601', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.7, lengthFt: 1.1, heightFt: 2.2 },
        { name: 'Baileigh DP-15VSF', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.7, lengthFt: 2.5, heightFt: 5.9 },
        { name: 'Baileigh DP-1500G', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.7, lengthFt: 2.0, heightFt: 6.25 },
        { name: 'Baileigh DP-3814B', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.8, lengthFt: 1.2, heightFt: 3.3 },
        { name: 'Baileigh DP-4016B', category: 'Drilling & Boring', layer: 'tools', widthFt: 0.9, lengthFt: 1.3, heightFt: 3.4 },
        { name: 'Baileigh DP-1375VS-110', category: 'Drilling & Boring', layer: 'tools', widthFt: 1.7, lengthFt: 2.0, heightFt: 6.25 },
        { name: 'JET JWL-1221VS', category: 'Turning', layer: 'tools', widthFt: 1.5, lengthFt: 3.3, heightFt: 1.5 },
        { name: 'Grizzly G0733', category: 'Turning', layer: 'tools', widthFt: 1.7, lengthFt: 5.5, heightFt: 4.0 },
        { name: 'Bosch RA1181', category: 'Routing', layer: 'tools', widthFt: 2.25, lengthFt: 1.5, heightFt: 1.2 },
        { name: 'Onefinity Journeyman', category: 'CNC & Digital Fab', layer: 'tools', widthFt: 2.7, lengthFt: 4.0, heightFt: 1.5 },
        { name: 'WEN DC3401', category: 'Dust Collection', layer: 'dust-collection', widthFt: 2.9, lengthFt: 1.1, heightFt: 1.2 },
        { name: 'Laguna C-Flux 2', category: 'Dust Collection', layer: 'dust-collection', widthFt: 3.8, lengthFt: 2.3, heightFt: 6.6 },

        // Mechanical/automotive shop equipment — new Shop Type feature, 2026-07-18
        { name: 'BendPak XPR-10A', category: 'Vehicle Lifts', layer: 'tools', domain: 'mechanical', widthFt: 12.0, lengthFt: 5.0, heightFt: 12.0 },
        { name: 'BendPak HD-9', category: 'Vehicle Lifts', layer: 'tools', domain: 'mechanical', widthFt: 9.2, lengthFt: 16.7, heightFt: 7.3 },
        { name: 'BendPak MD-6XP', category: 'Vehicle Lifts', layer: 'tools', domain: 'mechanical', widthFt: 6.0, lengthFt: 3.0, heightFt: 0.5 },
        { name: 'Ranger RML-1500XL', category: 'Vehicle Lifts', layer: 'tools', domain: 'mechanical', widthFt: 2.5, lengthFt: 6.6, heightFt: 0.7 },
        { name: 'Hobart Handler 140', category: 'Welding', layer: 'tools', domain: 'mechanical', widthFt: 0.9, lengthFt: 1.6, heightFt: 1.0 },
        { name: 'Miller Multimatic 215', category: 'Welding', layer: 'tools', domain: 'mechanical', widthFt: 0.9, lengthFt: 1.7, heightFt: 1.0 },
        { name: 'California Air Tools 10020C', category: 'Air Compressors & Shop Air', layer: 'tools', domain: 'mechanical', widthFt: 1.3, lengthFt: 1.3, heightFt: 3.0 },
        { name: 'Ingersoll Rand 2475N7.5-V', category: 'Air Compressors & Shop Air', layer: 'tools', domain: 'mechanical', widthFt: 3.2, lengthFt: 2.0, heightFt: 5.75 },
        { name: 'Torin T32002', category: 'Jacks & Lifting Equipment', layer: 'tools', domain: 'mechanical', widthFt: 5.3, lengthFt: 3.3, heightFt: 5.0 },
        { name: 'Arcan XL20', category: 'Jacks & Lifting Equipment', layer: 'tools', domain: 'mechanical', widthFt: 2.2, lengthFt: 0.5, heightFt: 1.1 },
        { name: 'Torin TRA4055', category: 'Jacks & Lifting Equipment', layer: 'tools', domain: 'mechanical', widthFt: 1.6, lengthFt: 4.1, heightFt: 2.9 },
        { name: 'Coats 70X-AH', category: 'Diagnostic & Specialty Equipment', layer: 'tools', domain: 'mechanical', widthFt: 4.0, lengthFt: 4.0, heightFt: 6.5 },
        { name: 'Snap-on EPIQ 84in', category: 'Mechanic Tool Storage', layer: 'tools', domain: 'mechanical', widthFt: 7.0, lengthFt: 2.5, heightFt: 6.0 },
        { name: 'Mac Tools Macsimizer', category: 'Mechanic Tool Storage', layer: 'tools', domain: 'mechanical', widthFt: 5.55, lengthFt: 2.25, heightFt: 3.9 },

        // Plumbing layer — domain-agnostic (no `domain` key), works for every shop type
        { name: 'Zurn Z415', category: 'Plumbing', layer: 'plumbing', widthFt: 0.7, lengthFt: 0.7, heightFt: 0.3 },
        { name: 'Mustee 63M', category: 'Plumbing', layer: 'plumbing', widthFt: 2.0, lengthFt: 0.83, heightFt: 2.0 },
        { name: 'Rheem RTEX-13', category: 'Plumbing', layer: 'plumbing', widthFt: 0.7, lengthFt: 0.3, heightFt: 1.05 },
        { name: 'NDS Dura Slope', category: 'Plumbing', layer: 'plumbing', widthFt: 0.5, lengthFt: 4.0, heightFt: 0.65 },
        { name: 'Woodford Model 65', category: 'Plumbing', layer: 'plumbing', widthFt: 0.3, lengthFt: 0.3, heightFt: 0.3 },

        { name: '4in-6in Duct Reducer', category: 'Dust Collection', layer: 'dust-collection', domain: 'woodworking', widthFt: 0.45, lengthFt: 0.6, heightFt: 7.0 }
    ];
})();
